"""证券金融分析应用的公共数据契约。"""

from .contracts import MarketBar, MarketDataSeries, MarketDataValidationError
from .market_data import (
    AkShareTencentDailyAdapter,
    DailyBarQuery,
    DailyMarketDataTool,
    JsonDailyMarketDataAdapter,
    MarketDataErrorCode,
    MarketDataFetchPolicy,
    MarketDataFetchResult,
    MarketDataProviderError,
    MarketDataRequestError,
)
from .data_hub import (
    SUPPORTED_FINANCIAL_DATASETS,
    FinancialDataError,
    FinancialDataErrorCode,
    FinancialDataHub,
    FinancialDataPolicy,
    FinancialDataRecord,
    FinancialDatasetResult,
    FinancialDataTool,
    FixtureFinancialDataProvider,
    JsonFinancialDataCache,
    SlidingWindowRateLimiter,
    SubprocessFinancialDataProvider,
    build_default_financial_data_tool,
)
from .mcp_server import create_financial_mcp_server
from .technical import (
    InsufficientMarketDataError,
    TechnicalAnalysisAgent,
    TechnicalAnalysisEngine,
    TechnicalAnalysisError,
    TechnicalAnalysisResult,
    TechnicalSignalComponent,
)
from .technical_runtime import (
    TECHNICAL_TOOL_OUTPUT_SCHEMA,
    TechnicalAnalysisQuery,
    TechnicalAnalysisRuntime,
    TechnicalAnalysisWorkflowResult,
    build_default_technical_analysis_runtime,
    validate_technical_analysis_output,
)
from .fundamental import (
    DATASETS,
    FundamentalAnalysisEngine,
    FundamentalAnalysisError,
)
from .fundamental_runtime import (
    DATASET_KEYS,
    FUNDAMENTAL_TOOL_OUTPUT_SCHEMA,
    FundamentalAnalysisQuery,
    FundamentalAnalysisRuntime,
    FundamentalAnalysisWorkflowResult,
    build_default_fundamental_analysis_runtime,
    validate_fundamental_analysis_output,
)
from .industry import (
    INDUSTRY_CHAIN_TAXONOMY,
    IndustryAnalysisEngine,
    IndustryAnalysisError,
)
from .industry_runtime import (
    INDUSTRY_DATASET_KEYS,
    INDUSTRY_TOOL_OUTPUT_SCHEMA,
    IndustryAnalysisQuery,
    IndustryAnalysisRuntime,
    IndustryAnalysisWorkflowResult,
    build_default_industry_analysis_runtime,
    validate_industry_analysis_output,
)
from .macro import MacroAnalysisEngine, MacroAnalysisError
from .macro_runtime import (
    MACRO_DATASET_KEYS,
    MACRO_TOOL_OUTPUT_SCHEMA,
    MacroAnalysisQuery,
    MacroAnalysisRuntime,
    MacroAnalysisWorkflowResult,
    build_default_macro_analysis_runtime,
    validate_macro_analysis_output,
)

__all__ = [
    "MarketBar",
    "MarketDataSeries",
    "MarketDataValidationError",
    "AkShareTencentDailyAdapter",
    "DailyBarQuery",
    "DailyMarketDataTool",
    "JsonDailyMarketDataAdapter",
    "MarketDataErrorCode",
    "MarketDataFetchPolicy",
    "MarketDataFetchResult",
    "MarketDataProviderError",
    "MarketDataRequestError",
    "SUPPORTED_FINANCIAL_DATASETS",
    "FinancialDataError",
    "FinancialDataErrorCode",
    "FinancialDataHub",
    "FinancialDataPolicy",
    "FinancialDataRecord",
    "FinancialDatasetResult",
    "FinancialDataTool",
    "FixtureFinancialDataProvider",
    "JsonFinancialDataCache",
    "SlidingWindowRateLimiter",
    "SubprocessFinancialDataProvider",
    "build_default_financial_data_tool",
    "create_financial_mcp_server",
    "InsufficientMarketDataError",
    "TechnicalAnalysisAgent",
    "TechnicalAnalysisEngine",
    "TechnicalAnalysisError",
    "TechnicalAnalysisResult",
    "TechnicalSignalComponent",
    "TECHNICAL_TOOL_OUTPUT_SCHEMA",
    "TechnicalAnalysisQuery",
    "TechnicalAnalysisRuntime",
    "TechnicalAnalysisWorkflowResult",
    "build_default_technical_analysis_runtime",
    "validate_technical_analysis_output",
    "DATASETS",
    "FundamentalAnalysisEngine",
    "FundamentalAnalysisError",
    "DATASET_KEYS",
    "FUNDAMENTAL_TOOL_OUTPUT_SCHEMA",
    "FundamentalAnalysisQuery",
    "FundamentalAnalysisRuntime",
    "FundamentalAnalysisWorkflowResult",
    "build_default_fundamental_analysis_runtime",
    "validate_fundamental_analysis_output",
    "INDUSTRY_CHAIN_TAXONOMY",
    "IndustryAnalysisEngine",
    "IndustryAnalysisError",
    "INDUSTRY_DATASET_KEYS",
    "INDUSTRY_TOOL_OUTPUT_SCHEMA",
    "IndustryAnalysisQuery",
    "IndustryAnalysisRuntime",
    "IndustryAnalysisWorkflowResult",
    "build_default_industry_analysis_runtime",
    "validate_industry_analysis_output",
    "MacroAnalysisEngine",
    "MacroAnalysisError",
    "MACRO_DATASET_KEYS",
    "MACRO_TOOL_OUTPUT_SCHEMA",
    "MacroAnalysisQuery",
    "MacroAnalysisRuntime",
    "MacroAnalysisWorkflowResult",
    "build_default_macro_analysis_runtime",
    "validate_macro_analysis_output",
]
